/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendadosRouteImport } from './routes/agendados'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ExportarRouteImport } from './routes/exportar'
import { Route as ClienteIdRouteImport } from './routes/cliente.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendadosRoute = AgendadosRouteImport.update({
  id: '/agendados',
  path: '/agendados',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportarRoute = ExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIdRoute = ClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendados': typeof AgendadosRoute
  '/clientes': typeof ClientesRoute
  '/exportar': typeof ExportarRoute
  '/cliente/$id': typeof ClienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendados': typeof AgendadosRoute
  '/clientes': typeof ClientesRoute
  '/exportar': typeof ExportarRoute
  '/cliente/$id': typeof ClienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendados': typeof AgendadosRoute
  '/clientes': typeof ClientesRoute
  '/exportar': typeof ExportarRoute
  '/cliente/$id': typeof ClienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agendados' | '/clientes' | '/exportar' | '/cliente/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agendados' | '/clientes' | '/exportar' | '/cliente/$id'
  id:
    '__root__' | '/' | '/agendados' | '/clientes' | '/exportar' | '/cliente/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendadosRoute: typeof AgendadosRoute
  ClientesRoute: typeof ClientesRoute
  ExportarRoute: typeof ExportarRoute
  ClienteIdRoute: typeof ClienteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendados': {
      id: '/agendados'
      path: '/agendados'
      fullPath: '/agendados'
      preLoaderRoute: typeof AgendadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportar': {
      id: '/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof ExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/$id': {
      id: '/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/cliente/$id'
      preLoaderRoute: typeof ClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendadosRoute: AgendadosRoute,
  ClientesRoute: ClientesRoute,
  ExportarRoute: ExportarRoute,
  ClienteIdRoute: ClienteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
